DELETE FROM MapStartPositions WHERE Map="{0ffac96e-140c-4389-8ae8-6c0cd6391c40}Maps/Giant Earth/PTW_GiantEarth_WB.Civ6Map" AND Plot="9066" AND Type="CIVILIZATION" AND Value="CIVILIZATION_NETHERLANDS" AND NOT EXISTS (SELECT * FROM Players WHERE CivilizationType="CIVILIZATION_NETHERLANDS");

INSERT OR REPLACE INTO MapStartPositions (Map, Plot, Type, Value)
SELECT	("{0ffac96e-140c-4389-8ae8-6c0cd6391c40}Maps/Giant Earth/PTW_GiantEarth_WB.Civ6Map"), ("9066"), ("CIVILIZATION"), ("CIVILIZATION_AMSTERDAM")
WHERE NOT EXISTS (SELECT * FROM Players WHERE CivilizationType="CIVILIZATION_NETHERLANDS");