INSERT OR REPLACE INTO MapStartPositions (Map, Plot, Type, Value)
SELECT	("{0ffac96e-140c-4389-8ae8-6c0cd6391c40}Maps/Giant Earth/PTW_GiantEarth_WB.Civ6Map"), ("6395"), ("CIVILIZATION"), ("CIVILIZATION_BABYLON")
WHERE EXISTS (SELECT * FROM Players WHERE CivilizationType="CIVILIZATION_BABYLON_STK");

DELETE FROM MapStartPositions WHERE Map="{0ffac96e-140c-4389-8ae8-6c0cd6391c40}Maps/Giant Earth/PTW_GiantEarth_WB.Civ6Map" AND Plot="6541" AND Type="CIVILIZATION" AND Value="CIVILIZATION_BABYLON_STK" AND NOT EXISTS (SELECT * FROM Players WHERE CivilizationType="CIVILIZATION_BABYLON_STK");

INSERT OR REPLACE INTO MapStartPositions (Map, Plot, Type, Value)
SELECT	("{0ffac96e-140c-4389-8ae8-6c0cd6391c40}Maps/Giant Earth/PTW_GiantEarth_WB.Civ6Map"), ("6541"), ("CIVILIZATION"), ("CIVILIZATION_BABYLON")
WHERE NOT EXISTS (SELECT * FROM Players WHERE CivilizationType="CIVILIZATION_BABYLON_STK");